### ISSUE TITLE
Question about audience

### ISSUE THREAD

**Issue by bathos** [tc39/template-for-proposals#10]
The readme establishes that this template is for TC39 members. But back in August, before this repo had anything in it, it was suggested to me that I watch this repo so that I could use it to help write [a proposal](https://github.com/bathos/object-from-entries), though I am not a member. Does this repo still have any relevance to non-members?

**Comment by ljharb** [comment]
TC39 members can co-champion a proposal written by non-members; in other words, this repo is relevant to non-members who have, or are seeking to get, a TC39 member to co-champion with them.

**Comment by bathos** [comment]
Thanks, that clears it up! (though perhaps the language is a little misleading then? not sure).

**Comment by ljharb** [comment]
If you have suggestions about how to clear it up, I'd be happy to incorporate them!
