### ISSUE TITLE
"You are a member of TC39" - or contributor?

### ISSUE THREAD

**Issue by tjcrowder** [tc39/template-for-proposals#11]
Under *Before creating a proposal*, the template says:

> Please ensure the following:
> * You are a member of TC39
> * ...

Is the template really intended only for use by TC39 members, or is that meant to mean a member of TC39 **or** a [TC39 ECMAScript RFTG Contributor](https://tc39.github.io/agreements/contributor/)?

If the latter, I'll do a PR to update it.

Thanks.

**Comment by ljharb** [comment]
Only members can champion proposals; the target audience for this template is delegates (not contributors)

**Comment by tjcrowder** [comment]
@ljharb - Okay, thanks. I was thinking this was a good starting point for people looking to put something forward for Stage 0 (obviously they wouldn't do much spec text initially), sort of a "start out as you mean to go on" thing. But I take it it's meant for Stage 1.

**Comment by ljharb** [comment]
It’s meant for stage 0; but stage 0 proposals also need delegate champions.

**Comment by tjcrowder** [comment]
@ljharb - That seems at odds with [the process document](https://tc39.github.io/process-document/), which lists no entrance criteria for Stage 0 but does list a TC39 champion as one of the criteria for Stage 1.

**Comment by ljharb** [comment]
Ah, fair point. It does say “Such submissions must either come from members of TC39 or from non-members who have registered via Ecma International.” - so that suggests that stage 0 proposals can also come from registered contributors, although that’s not typically how it’s been done.

**Comment by tjcrowder** [comment]
@ljharb - So do you want to encourage use only by TC39, or is it worth pointing people at this as a starting point even for Stage 0 suggestions from outside the committee? I like the idea of having something a bit more formal to point people at as compared to the usually-quite-incomplete-and-lacking-research emails we see on es-discuss. But if you think it shouldn't be this, no worries.

**Comment by ljharb** [comment]
I think that eventually that’d be great; community-authored proposals in the proper format are easier for delegates to champion. However, i think it’s still way too early to do that; we’re still trying to get all the delegates onboard.

**Comment by tjcrowder** [comment]
@ljharb - That's interesting. :-) Okay, cool, I'll leave it there. Thanks for your efforts on JS!
