### ISSUE TITLE
Refining language: "You are a member of TC39"

### ISSUE THREAD

**Issue by rwaldron** [tc39/template-for-proposals#12]
Since there is really no such thing as a "member of TC39" or "TC39 members", I'd like to suggest a minor language revision: "You are a TC39 member organization delegate"

WDYT?

**Comment by ljharb** [comment]
Companies are members, but you’re right that this would be a good clarification.

**Comment by mikesamuel** [comment]
A link to how-we-work/join-tc39.md might provide sufficient context once it's ready to go.

**Comment by ljharb** [comment]
Done in #22.
