### ISSUE TITLE
Maybe use `pre-commit` to auto install hooks

### ISSUE THREAD

**Issue by mikesamuel** [tc39/template-for-proposals#14]
https://www.npmjs.com/package/pre-commit

> pre-commit is a pre-commit hook installer for git. It will ensure that your npm test (or other specified scripts) passes before you can commit your changes. This all conveniently configured in your package.json.

So if the package.json listed pre-commit as a devDependency and included
```json
  "pre-commit": [
    "build"
  ],
```

you could do away with this language from the README:

> 4. Add a post-rewrite git hook to auto-rebuild the output on every commit:
>       cp hooks/post-rewrite .git/hooks/post-rewrite
>       chmod +x .git/hooks/post-rewrite

I'm happy to send a PR your way

**Comment by ljharb** [comment]
I am very much against any sort of package that installs git hooks implicitly - there's a reason git doesn't function that way; I find it very unsafe.

**Comment by mikesamuel** [comment]
Fair enough.

**Comment by ljharb** [comment]
(To be clear, thank you for the suggestion, and if there's a way to make it easier to install the hook explicitly i'm all for that)

**Comment by mikesamuel** [comment]
That's a legitimate concern.  Other ecosystems have had serious breaches due to dodgy hooks.

For small, personal projects where I'm the only committer, I'm more worried about checking out a fresh client and missing something.
