### ISSUE TITLE
Recommend that explainer point to GH pages

### ISSUE THREAD

**Issue by mikesamuel** [tc39/template-for-proposals#16]
Since you don't assume familiarity with GH pages elsewhere, maybe something like

"""

In your explainer, point readers to the `index.html` generated from `spec.emu` via markdown like

```
You can browse the [ecmarkup output](https://ACCOUNT.github.io/PROJECT/)
or browse the [source](https://github.com/ACCOUNT/PROJECT/blob/master/spec.emu).
```

where *ACCOUNT* and *PROJECT* are the first two path elements in your project's Github URL.
For example, for `github.com/tc39/template-for-proposals`, *ACCOUNT* is `tc39` and *PROJECT* is `template-for-proposals`.

"""

**Comment by ljharb** [comment]
That sounds like a great idea.

**Comment by ljharb** [comment]
Done in #17.
