### ISSUE TITLE
no hooks/post-rewrite 

### ISSUE THREAD

**Issue by ahmetcetin** [tc39/template-for-proposals#19]
There is no hooks/post-rewrite file in the repo. If it's removed intentionally then read me should be changed.

**Comment by ljharb** [comment]
Thanks for filing; I’m aware of the problem. It is not removed intentionally; i have to reconstruct the hook and add it to the repo.

**Comment by decompil3d** [comment]
_nag nag nag_ 😉

**Comment by ljharb** [comment]
k, i've removed this language from the readme, and added a github action that should automatically push up a commit with the build output (in fork PR branches, too).
