### ISSUE TITLE
No need to have a separate .css and .js files

### ISSUE THREAD

**Issue by littledan** [tc39/template-for-proposals#2]
New versions of ecmarkup will build these into the same single HTML output file, since the separate files proved hard to maintain, resulting in many broken spec documents. You just don't need these files at all.

**Comment by ljharb** [comment]
Interesting; this is a bug to me: https://github.com/bterlson/ecmarkup/issues/119

It's fine if omitting `--js` or `--css` causes them to be inlined, but when supplied they should be *not* inlined.

It does seem simpler tho to avoid the separate files; I'll update the template to address that.

**Comment by littledan** [comment]
Thanks for the fix.
