### ISSUE TITLE
Generated html should be checked into gh-pages branch

### ISSUE THREAD

**Issue by littledan** [tc39/template-for-proposals#3]
It seems to be checked into the master branch here.

**Comment by ljharb** [comment]
That's intentional; there's no need for a separate gh-pages branch at all; this way, github pages is never out of date.

The instructions in the read me describe this in step 2 under https://github.com/tc39/template-for-proposals#create-your-proposal-repo.

**Comment by littledan** [comment]
Have you applied these instructions on this repo? I don't see it really working. Is this the right URL? http://tc39.github.io/template-for-proposals/

**Comment by littledan** [comment]
Overall, I still think it's cleaner to have a separate branch for rendering the proposal; it gives a nicer commit history. But this is an unimportant point; we don't preserve the commit history when merging into the main spec.

**Comment by ljharb** [comment]
Pages always takes a minute or two to update after the branch is updated.

The commit history on gh-pages branches, in my experience, either ends up being "updating the spec" (useless) or repeating the commit messages from the main repo (redundant).

The goal is that any ecmarkup changes made should always be accompanied by re-built HTML.

**Comment by ljharb** [comment]
The instructions for this repo are in the readme; there's no github pages for it because there's no index.html.
