### ISSUE TITLE
Unclear setup steps for GH pages

### ISSUE THREAD

**Issue by nicolo-ribaudo** [tc39/template-for-proposals#37]
> Under the “Pages” section on the left sidebar, and set the source to “deploy from a branch” and check “Enforce HTTPS”

However, I don't have an "Enforce HTTPS" checkbox.

<img width="975" alt="image" src="https://github.com/user-attachments/assets/6b0069e2-f92e-4243-b6e8-2257c66651b5">

**Comment by ljharb** [comment]
hm, what happens if you select a branch in the dropdown (gh-pages, presumably)?

**Comment by nicolo-ribaudo** [comment]
Oh yes, then it appears. The repository is currently on my personal account, and HTTPS is enabled by default and cannot be disabled:
<img width="975" alt="image" src="https://github.com/user-attachments/assets/66396702-c3be-460d-8b0f-5ced83999a16">

**Comment by ljharb** [comment]
Gotcha, I'll update the instructions.
