### ISSUE TITLE
Include advice on writing an explainer document? Or is that out of scope?

### ISSUE THREAD

**Issue by littledan** [tc39/template-for-proposals#4]
Proposals should typically come with an explainer document first, exploring issues within bugs, and then writing spec text after. Should this be documented somewhere within this template, or is that best left for a separate guide?

**Comment by ljharb** [comment]
I think that would be a great addition to [this section](https://github.com/tc39/template-for-proposals#maintain-your-proposal-repo) - PRs welcome :-D

**Comment by ljharb** [comment]
Done in #17.
