### ISSUE TITLE
Include information on how to write a specification (or is this out of scope?)

### ISSUE THREAD

**Issue by littledan** [tc39/template-for-proposals#8]
For example
- How specific should a well-written specification be?
- What is the division of information between the specification and explainer?
- How to use ecmarkup, including algorithm and grammar notation
- What are the ECMAScript algorithmic conventions
- What are some basic invariants/concerns that we try to maintain for new language features

**Comment by ljharb** [comment]
I think it's "out of scope" in that it's not necessary, but I also think this would be a useful place to document these things, or at least link to them elsewhere.

**Comment by ljharb** [comment]
Now that we have how-we-work, I think that's where that should go. A PR to link to any helpful resources is always welcome.
