### ISSUE TITLE
Meta: Should this repo document current practice or point a good way to the future?

### ISSUE THREAD

**Issue by littledan** [tc39/template-for-proposals#9]
A few of the bugs (#3, #5, #6) point to ways that this proposal recommends doing things which don't seem to be done by the majority of proposal authors today. I see two ways to look at the purpose of this repository with respect to those issues:
- This repository should document current practice, so that beginners can do things like existing proposals.
- This repository should point a way to the future, documenting things that would be better than current practices.

I'm more inclined to the first goal for this repository: the idea would be to keep this repository's goals narrow, and pursue changes by convincing other committee members, then documenting the results. As things are now, it seems like this repository is following more like the second goal, where @ljharb is documenting different practices that are not followed by most repositories.

**Comment by domenic** [comment]
I am generally worried about this issue, but less than I thought I would be. In particular @ljharb hasn't wholesale ported some of his idiosyncratic preferences such as duplicating the spec in Markdown, which I'm glad about :). Of the issues you list, only #6 worries me. I liberally-license all my specs (or maybe I've forgotten a couple?) and I think that while we could perhaps point people to the auto-deploy setup, it's too much to ask if we're hoping this template's goal is to make things easier.

**Comment by ljharb** [comment]
Lol yeah the markdown thing isn’t reasonable to ask people to do manually; if i can come up with a process to generate it from the ecmarkup, then I’d want to add that here (since it makes things more readable in-repo).

In general, i think it should be the second goal - documenting current practices is unnecessary since you can infer those from existing proposals. This repo is meant to look towards the future, not the past.

**Comment by littledan** [comment]
I thought part of the point was that it was unclear what to infer from existing repos.

I've given some feedback on the patterns you are encouraging here; I'm wondering how you plan to gather more feedback so you can decide on what the recommendations should be.

**Comment by ljharb** [comment]
I hope to gather more feedback by gradually asking for it from wider and wider circles, with the goal that changes aren't needed by the time it gets to a wide audience.

**Comment by ljharb** [comment]
6 years later I think any feedback can continue to be filed as separate issues; the goal of this repo is to help *new* proposals, not current ones.
